name: jono
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2


  cupertino_icons: ^1.0.2
  custom_info_window: ^1.0.1
  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/map_style/
    - assets/svgs/
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
